# /etc/nginx/sites-enabled/copyparty
upstream cpp_tcp {
    server 127.0.0.1:3923 fail_timeout=1s;
    keepalive 1;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name files.parapalli.dev;

    ssl_certificate     /etc/ssl/cloudflare/origin.pem;
    ssl_certificate_key /etc/ssl/cloudflare/origin.key;

    # Only allow Cloudflare IPs
    include /etc/nginx/cloudflare-only.conf;

    # Restore real visitor IP from Cloudflare header
    real_ip_header CF-Connecting-IP;

    location / {
        proxy_pass http://cpp_tcp;
        proxy_redirect off;

        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_request_buffering off;

        proxy_buffers 32 8k;
        proxy_buffer_size 16k;
        proxy_busy_buffers_size 24k;

        proxy_set_header Connection        "Keep-Alive";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For   $http_cf_connecting_ip;
    }
}

# Redirect plain HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name files.parapalli.dev;

    include /etc/nginx/cloudflare-only.conf;

    return 301 https://$host$request_uri;
}

client_max_body_size 1024M;
client_header_timeout 610m;
client_body_timeout 610m;
send_timeout 610m;